name: Run Rust Tests

on:
  pull_request:
    types: [opened, edited, synchronize]
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code de la branche
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer Rust
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Étape 3 : Vérifier la qualité du code avec cargo fmt (facultatif)
      - name: Run Cargo fmt
        run: cargo fmt -- --check

      # Étape 4 : Lancer les tests avec cargo test
      - name: Run tests
        run: cargo test --verbose
